#!/bin/sh

PREREQ=""

prereqs()
{
    echo "$PREREQ"
}

case $1 in
prereqs)
    prereqs
    exit 0
    ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /bin/gunzip /sbin
copy_exec /bin/sync /bin
copy_exec /bin/lsblk /bin
copy_exec /bin/sleep /bin
copy_exec /sbin/mkfs.ext3 /sbin
copy_exec /sbin/mke2fs.ext3 /sbin
copy_exec /sbin/blkid /sbin
copy_exec /sbin/fdisk /sbin
