#!/bin/sh

CONFIG=$ROOTDIR/$LINUXDIR/.config
if [ -f $CONFIG ] 
then
	source $CONFIG
fi

cons="  admin admin 622"
disk="  admin admin 660"
null="  admin admin 666"
urandom="  admin admin  644"
mkdev () {    # usage: mkdev name [bcu] major minor owner group mode
        if [ "$opt_v" ]
        then    if [ "$opt_d" ]
                then    echo "rm -f $1"
                else    echo "$1        = $2 $3 $4 $5:$6 $7"
                fi
        fi
        [ ! "$opt_n" ] && rm -f $1 &&
        [ ! "$opt_d" ] && mknod $1 $2 $3 $4 &&
                chown $5:$6 $1 &&
                chmod $7 $1
}  
cd $1

mkdev	dev/ram	    b	1   1	$disk 
mkdev	dev/ram0    b	1   0	$disk
mkdev	dev/ram1    b	1   1	$disk 
mkdev	dev/ram2    b	1   2	$disk
mkdev	dev/ram3    b	1   3	$disk

mkdev	dev/mem     c	1   1	$disk
mkdev	dev/kmem    c	1   2	$null
mkdev	dev/null    c	1   3	$null
mkdev	dev/random  c	1   8	$urandom
mkdev	dev/urandom c   1   9   $urandom
mkdev	dev/zero c   1   5   $urandom


mkdev	dev/ptyp0   c	2   0	$urandom
mkdev	dev/ptyp1   c	2   1	$urandom

mkdev	dev/ttyp0   c	3   0	$urandom
mkdev	dev/ttyp1   c	3   1	$urandom

mkdev	dev/ptmx    c	5   2	$null

mkdev	dev/ttyS0   c	4   64	$cons
mkdev	dev/ttyS1   c	4   65	$cons
mkdev	dev/console c   5   1   $cons

# for Option Icon 225 3G dongle
if [ "$CONFIG_USB_SERIAL_HSO" = "y" ] || [ "$CONFIG_USB_SERIAL_HSO" = "m" ]; then
	mkdev	dev/ttyHS0   c	245 0	$cons
	mkdev	dev/ttyHS1   c	245 1	$cons
	mkdev	dev/ttyHS2   c	245 2	$cons
	mkdev	dev/ttyHS3   c	245 3	$cons
fi

# for generic 3G dongle
if [ "$CONFIG_USB_SERIAL" = "y" ] || [ "$CONFIG_USB_SERIAL" = "m" ]; then
	mkdev	dev/ttyUSB0   c	188 0	$cons
	mkdev	dev/ttyUSB1   c	188 1	$cons
	mkdev	dev/ttyUSB2   c	188 2	$cons
	mkdev	dev/ttyUSB3   c	188 3	$cons
fi

# for BandLuxe 3G dongle
if [ "$CONFIG_BLK_DEV_SR" = "y" ] || [ "$CONFIG_BLK_DEV_SR" = "m" ]; then
mkdev	dev/sr0	    b	11  0	$cons
fi
if [ "$CONFIG_CHR_DEV_SG" = "y" ] || [ "$CONFIG_CHR_DEV_SG" = "m" ]; then
mkdev	dev/sg0	    c	21  0	$cons
fi

mkdev   dev/mtdblock0 b  31 0 $disk
mkdev   dev/mtdblock1 b  31 1 $disk
mkdev   dev/mtdblock2 b  31 2 $disk
mkdev   dev/mtdblock3 b  31 3 $disk
mkdev   dev/mtdblock4 b  31 4 $disk
mkdev   dev/mtdblock5 b  31 5 $disk
mkdev   dev/mtdblock6 b  31 6 $disk
mkdev   dev/oplkcfgA b  31 7 $disk
mkdev   dev/oplkcfgB b  31 8 $disk
mkdev   dev/oplkimageA b  31 9 $disk
mkdev   dev/oplkimageB b  31 10 $disk
mkdev   dev/mtd0      c  90 0 $disk
mkdev   dev/mtd0ro    c  90 1 $disk
mkdev   dev/mtd1      c  90 2 $disk
mkdev   dev/mtd1ro    c  90 3 $disk
mkdev   dev/mtd2      c  90 4 $disk
mkdev   dev/mtd2ro    c  90 5 $disk
mkdev   dev/mtd3      c  90 6 $disk
mkdev   dev/mtd3ro    c  90 7 $disk
mkdev   dev/mtd4      c  90 8 $disk
mkdev   dev/mtd4ro    c  90 9 $disk
mkdev   dev/mtd5      c  90 10 $disk
mkdev   dev/mtd5ro    c  90 11 $disk
mkdev   dev/mtd6      c  90 12 $disk
mkdev   dev/mtd6ro    c  90 13 $disk
mkdev   dev/mtd7      c  90 14 $disk
mkdev   dev/mtd7ro    c  90 15 $disk
mkdev   /dev/mtd8      c  90 16 $disk
mkdev   /dev/mtd8ro    c  90 17 $disk
mkdev   /dev/mtd9      c  90 18 $disk
mkdev   /dev/mtd9ro    c  90 19 $disk
mkdev   /dev/mtd10      c  90 20 $disk
mkdev   /dev/mtd10ro    c  90 21 $disk


mkdev	/dev/video0  c	81	0   $cons
mkdev	/dev/video1  c	81	1   $cons
mkdev	dev/ppp	    c	108	0   $cons
mkdev	dev/pts/0   c	136	0   $cons 
mkdev	dev/pts/1   c	136	1   $cons 
mkdev	dev/pts/2   c	136	2   $cons 
mkdev	dev/pts/3   c	136	3   $cons 
mkdev   dev/spiS0   c   217     0   $cons
mkdev   dev/i2cM0   c   218     0   $cons

mkdev	dev/flash0  c	200	0   $cons
mkdev	dev/swnat0  c	210	0   $cons
mkdev	dev/hwnat0  c	220	0   $cons
mkdev	dev/acl0    c	230	0   $cons
mkdev	dev/ac0	    c	240	0   $cons
mkdev	dev/mtr0    c	250	0   $cons
mkdev   dev/nvram   c   251     0   $cons
mkdev	dev/gpio    c	252	0   $cons
mkdev	dev/rdm0    c	253	0   $cons
mkdev	dev/watchdog   c 10   130   $cons
mkdev   dev/pcm0        c 233   0       $cons
mkdev   dev/i2s0        c 234   0   $cons
mkdev	dev/cls0	c 235	0	$cons

mkdir	-p /dev/snd
mkdev	/dev/snd/controlC0 c 116 0 $null
mkdev	/dev/snd/controlC1 c 116 32 $null
mkdev	/dev/snd/seq c 116 1 $null
mkdev	/dev/snd/pcmC0D0p c 116 16 $null
mkdev	/dev/snd/pcmC0D0c c 116 24 $null
mkdev	/dev/snd/pcmC0D1c c 116 25 $null
mkdev	/dev/snd/pcmC1D0c c 116 56 $null
mkdev	/dev/snd/pcmC1D0p c 116 48 $null
mkdev	/dev/snd/timer c 116 33 $null

mkdev	/dev/sda	b 8 0 $null
mkdev	/dev/sda1	b 8 1 $null
mkdev	/dev/sda2	b 8 2 $null
mkdev	/dev/sda3	b 8 3 $null
mkdev	/dev/sda4	b 8 4 $null
mkdev	/dev/sdb	b 8 16 $null
mkdev	/dev/sdb1	b 8 17 $null
mkdev	/dev/sdb2	b 8 18 $null
mkdev	/dev/sdb3	b 8 19 $null
mkdev	/dev/sdb4	b 8 20 $null
mkdev	/dev/sdc	b 8 32 $null
mkdev	/dev/sdc1	b 8 33 $null
mkdev	/dev/sdc2	b 8 34 $null
mkdev	/dev/sdc3	b 8 35 $null
mkdev	/dev/sdc4	b 8 36 $null
mkdev	/dev/sdd	b 8 48 $null
mkdev	/dev/sdd1	b 8 49 $null
mkdev	/dev/sdd2	b 8 50 $null
mkdev	/dev/sdd3	b 8 51 $null
mkdev	/dev/sdd4	b 8 52 $null

#For SD card
mkdev	/dev/mmcblk0p1	b 179 1 $disk
#mkdev	/dev/mmcblk0	b 179 0 $disk
