-include feature/Information/rule.mk
-include feature/RestoreToDefault/rule.mk
-include feature/USBTest/rule.mk
-include feature/SDCardTest/rule.mk
-include feature/SendCommandLine/rule.mk
-include feature/GetIMEI/rule.mk
-include feature/GetRSSIStatus/rule.mk
